name: Deploy to production environment
on:
  push:
    branches:
      - production
jobs:
  deploy:
    environment: production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      SKAFFOLD_DEFAULT_REPO: 539850000317.dkr.ecr.eu-west-1.amazonaws.com
      KUBECONFIG: /tmp/config
      AWS_REGION: eu-west-1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Configure kubectl
        run: |
          set -e

          version=$(curl -Ls https://dl.k8s.io/release/stable.txt)
          echo "using kubectl@$version"

          curl -sLO "https://dl.k8s.io/release/$version/bin/linux/amd64/kubectl" -o kubectl
          chmod +x kubectl
          mv kubectl /usr/local/bin

          # Extract the base64 encoded config data and write this to the KUBECONFIG
          echo "$KUBE_CONFIG_DATA" | base64 -d > $KUBECONFIG

      - name: Configure skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/

      - name: Build and Deploy
        run: cd k8s && skaffold run -vdebug --profile production
